name: vostok
base: core18
version: '0.0.6'
license: LGPL-3.0
summary: Compiler from Oberon-07 to C/Java/Js/Oberon
description: |
  Translator of Oberon-07 code into readable or error-resistant
  code for a range of industrial programming languages, as well as machine code and
  intermediate representations.

grade: devel
confinement: classic

parts:
  ost:
    plugin: make
    makefile: 'snap/local/Makefile'

    source:
      .

apps:
  vostok:
    command: usr/bin/ost
